### ISSUE TITLE
How to add references?

### ISSUE THREAD

**Issue by orschiro** [larlequin/PandocAcademic#17]
Hi @larlequin,

Many thanks for PandocAcademic! I used the command provided to convert my document to PDF. 

However, it does not convert my references.

My frontmatter contains the following:

```
---  
title: title...
abstract: abstract....
date: December 15, 2014
bibliography: /home/orschiro/Mendeley/library.bib
csl: APA6.csl
---  
```

In the end of my document I added `#References`.

My references are successfully added when using the following command in my Linux shell:

```
pandoc -S -o output.pdf --filter pandoc-citeproc document.md
```

Is there any way to customise the provided Pandoc command to use the `--filter pandoc-citeproc` option?

Thanks for your advice!

Robert

**Comment by larlequin** [comment]
Dear Robert,

Thank you for your support. Regarding your question, did you included the bib and/or bibstyle command as presented in the readme file:

 : Add the bibliography option to handle citation and reference (@citationkey). The bibliography file should have the same name than the Pandoc file.
: Specify a csl bibliography style.

The plugin was not developed to handle yaml header so that I believe that you could not run the bibliography command within it. 

If you need more personnalisation,  I am no sure that Pandoc Academic could include them without any relatively heavy development.

Hope it helps.

Best,

Guillaume

**Comment by orschiro** [comment]
Hi Guillaume,

Thanks for your response.

> The plugin was not developed to handle yaml header so that I believe that you could not run the bibliography command within it. 

Now it's more clear although I cannot test it. I switched to [academicmarkdown](https://github.com/smathot/academicmarkdown) which is a very comprehensive package.

**Comment by larlequin** [comment]
Hi Robert,

You are welcome. AcademicMarkdown is good project for sure.

Best,

Guillaume
